### ISSUE TITLE
Kafka Stream stays in a "zombie" state although supervision strategy is to stop.

### ISSUE THREAD

**Issue by realvictorprm** [akkadotnet/Akka.Streams.Kafka#122]
Hi,

we're experiencing the issue that the stream stays in a zombie state as soon as connectivity to all brokers is lost (e.g. because not all brokers are available yet).
The dummy code for that scenario would be:
```
KafkaConsumer
   .CommitableSource(consumerSettings, subscription)
   .WithAttributes(ActorAttributes.CreateSupervisionStrategy(Akka.Streams.Supervision.Deciders.StoppingDecider))
   .Select(....)
   .RunWith(KafkaProducer.PlainSink(producerSettings).WithAttributes(ActorAttributes.CreateSupervisionStrategy(Akka.Streams.Supervision.Deciders.StoppingDecider)))
```

**Comment by IgorFedchenko** [comment]
@realvictorprm Thanks for taking time and giving sample code.

"stream stays in zombie state" - you mean the task you obtain from `RunWith` is not finished, keeps running? 
I tried to build full reproduction, but when I am shutting down the kafka service (stopping docker container), I have this Task completed (faulted, to be precise) - as it should. And same if I do not start kafka service at all (broker not available from the beginning).

So could you help me with more details about how to reproduce this case? Also, do you have some code sample more or less isolated from your domain, so that we could easier locate the actual reason?

**Comment by IgorFedchenko** [comment]
Closing this for now, but feel free to reopen this @realvictorprm

**Comment by realvictorprm** [comment]
Sorry, couldn't add more as I reported this bug as part of a customer project :sweat:
