### ISSUE TITLE
KafkaConsumer does not close on Stream Shutdown

### ISSUE THREAD

**Issue by ayoung** [akkadotnet/Akka.Streams.Kafka#130]
With the sample I provided in #129 the KafkaConsumer does not close when the stream is stopped because of an exception. For example when connection to Kafka is lost or never established. This seems to be specific to the usage of `DrainingControl` as without using that, the Consumer stops properly. Instead I get dead letters encountered.

```
[17:32:18 INF] Message [Poll`2] from akka://cce-outbound/system/kafka-consumer-2 to 
akka://cce-outbound/system/kafka-consumer-2 was not delivered. [1] dead letters encountered .
This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 
'akka.log-dead-letters-during-shutdown'.
```

**Comment by IgorFedchenko** [comment]
@ayoung Why do you think that consumer is not stopped? 

When something breaks in the stream during processing, shutdown process is triggered, and internal actors are shutting down. Including the `KafkaConsumerActor` that has `Poll` message scheduled to periodically poll messages from kafka.

So, it's just some `Poll` messages there were scheduled but could not be processed because actor is already terminated. This should be fine.
