### ISSUE TITLE
Consumer/Producer Settings Issue After Upgrading.

### ISSUE THREAD

**Issue by Sherburn** [akkadotnet/Akka.Streams.Kafka#147]
I have just upgraded from an older version (0.3.0), to the latest.

After the upgrade I have lost the following options in `ConsumerSettings` and `ProducerSettings`

ConsumerSettings:

**.AsAutoCommitted** and **.UseAvro**
```
var consumerSettings = new ConsumerSettings<long, MyMessageType>()
                .AsAutoCommitted(AppConfig.KafkaBootstrapServers)
                .UseAvro(AppConfig.AvroSchemaRegistry)
                .WithGroupId(AppConfig.KafkaGroupId);
```

ProducerSettings

**.AsSimpleProducer** and **.UseAvro**
```
var producerSettings = new ProducerSettings<long, MyMessageType>()
                .AsSimpleProducer(kafkaAddress)
                .UseAvro(avroAddress);
```

Appreciate this is an upgrade from a very early version.  But what should I be doing as a workaround for these options? I'm mainly interested in the Avro configuration.  Based on a look at the docs, it seems `.WithBootstrapServers` is now used to configure the Kafka server address.

All help/suggestions appreciated thanks.

**Comment by IgorFedchenko** [comment]
@Sherburn Hmm... I can not find version 0.3.0 in our source history, I beleave we started publishing nuget packages from verstion 0.5.0 (in beta state). And it seems like we did not have `AsSimpleProducer` or `UseAvro` methods on `ProducerSettings`, we had `WithBootstrapServers` to be used from the very beginning of this repository. Are you sure that this methods are from our package? Maybe they are some extention methods from other library?

Anyway, all of the methods of `ProducerSettings` are just a wrappers on `WithProperty(string key, string value)` method. Here is how kafka endpoint setup looks like:
```c#
public ProducerSettings<TKey, TValue> WithBootstrapServers(string bootstrapServers) =>
            WithProperty("bootstrap.servers", bootstrapServers);
```

So, you can set whatever configuration you want using this method. Just need to check out what that methods are basically setting up.

P.S. Since we are using Kafka Confluent driver internally to work with kafka, you can checkout configuration options available for [producer](https://docs.confluent.io/current/installation/configuration/producer-configs.html#cp-config-producer) and [consumer](https://docs.confluent.io/current/installation/configuration/consumer-configs.html).

Does it make sence?

**Comment by IgorFedchenko** [comment]
@Sherburn Let us know if you have any questions. Closing this issue so far.
